
package com.coverity.ws.v9;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConfigurationService", targetNamespace = "http://ws.coverity.com/v9")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConfigurationService {


    /**
     * 
     * @param componentMapSpec
     * @param componentMapId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateComponentMap", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateComponentMap")
    @ResponseWrapper(localName = "updateComponentMapResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateComponentMapResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateComponentMapRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateComponentMapResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateComponentMap/Fault/CovRemoteServiceException")
    })
    public void updateComponentMap(
            @WebParam(name = "componentMapId", targetNamespace = "")
            ComponentMapIdDataObj componentMapId,
            @WebParam(name = "componentMapSpec", targetNamespace = "")
            ComponentMapSpecDataObj componentMapSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentMapId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteComponentMap", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteComponentMap")
    @ResponseWrapper(localName = "deleteComponentMapResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteComponentMapResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteComponentMapRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteComponentMapResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteComponentMap/Fault/CovRemoteServiceException")
    })
    public void deleteComponentMap(
            @WebParam(name = "componentMapId", targetNamespace = "")
            ComponentMapIdDataObj componentMapId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param roleSpec
     * @param roleId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateRole", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateRole")
    @ResponseWrapper(localName = "updateRoleResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateRoleResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateRoleRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateRoleResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateRole/Fault/CovRemoteServiceException")
    })
    public void updateRole(
            @WebParam(name = "roleId", targetNamespace = "")
            RoleIdDataObj roleId,
            @WebParam(name = "roleSpec", targetNamespace = "")
            RoleSpecDataObj roleSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteProject", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteProject")
    @ResponseWrapper(localName = "deleteProjectResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteProjectResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteProjectRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteProjectResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteProject/Fault/CovRemoteServiceException")
    })
    public void deleteProject(
            @WebParam(name = "projectId", targetNamespace = "")
            ProjectIdDataObj projectId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param groupId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteGroup", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteGroup")
    @ResponseWrapper(localName = "deleteGroupResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteGroupResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteGroupRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteGroupResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteGroup/Fault/CovRemoteServiceException")
    })
    public void deleteGroup(
            @WebParam(name = "groupId", targetNamespace = "")
            GroupIdDataObj groupId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param roleId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteRole", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteRole")
    @ResponseWrapper(localName = "deleteRoleResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteRoleResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteRoleRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteRoleResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteRole/Fault/CovRemoteServiceException")
    })
    public void deleteRole(
            @WebParam(name = "roleId", targetNamespace = "")
            RoleIdDataObj roleId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectSpec
     * @param projectId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateProject", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateProject")
    @ResponseWrapper(localName = "updateProjectResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateProjectResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateProjectRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateProjectResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateProject/Fault/CovRemoteServiceException")
    })
    public void updateProject(
            @WebParam(name = "projectId", targetNamespace = "")
            ProjectIdDataObj projectId,
            @WebParam(name = "projectSpec", targetNamespace = "")
            ProjectSpecDataObj projectSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param attributeDefinitionId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteAttribute", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteAttribute")
    @ResponseWrapper(localName = "deleteAttributeResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteAttributeResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteAttributeRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteAttributeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteAttribute/Fault/CovRemoteServiceException")
    })
    public void deleteAttribute(
            @WebParam(name = "attributeDefinitionId", targetNamespace = "")
            AttributeDefinitionIdDataObj attributeDefinitionId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param attributeDefinitionId
     * @param attributeDefinitionSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateAttribute", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateAttribute")
    @ResponseWrapper(localName = "updateAttributeResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateAttributeResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateAttributeRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateAttributeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateAttribute/Fault/CovRemoteServiceException")
    })
    public void updateAttribute(
            @WebParam(name = "attributeDefinitionId", targetNamespace = "")
            AttributeDefinitionIdDataObj attributeDefinitionId,
            @WebParam(name = "attributeDefinitionSpec", targetNamespace = "")
            AttributeDefinitionSpecDataObj attributeDefinitionSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createStream", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateStream")
    @ResponseWrapper(localName = "createStreamResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateStreamResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createStreamRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createStream/Fault/CovRemoteServiceException")
    })
    public void createStream(
            @WebParam(name = "streamSpec", targetNamespace = "")
            StreamSpecDataObj streamSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createProject", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateProject")
    @ResponseWrapper(localName = "createProjectResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateProjectResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createProjectRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createProjectResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createProject/Fault/CovRemoteServiceException")
    })
    public void createProject(
            @WebParam(name = "projectSpec", targetNamespace = "")
            ProjectSpecDataObj projectSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param groupSpec
     * @param groupId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateGroup", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateGroup")
    @ResponseWrapper(localName = "updateGroupResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateGroupResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateGroupRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateGroupResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateGroup/Fault/CovRemoteServiceException")
    })
    public void updateGroup(
            @WebParam(name = "groupId", targetNamespace = "")
            GroupIdDataObj groupId,
            @WebParam(name = "groupSpec", targetNamespace = "")
            GroupSpecDataObj groupSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param roleSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createRole", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateRole")
    @ResponseWrapper(localName = "createRoleResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateRoleResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createRoleRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createRoleResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createRole/Fault/CovRemoteServiceException")
    })
    public void createRole(
            @WebParam(name = "roleSpec", targetNamespace = "")
            RoleSpecDataObj roleSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentMapSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createComponentMap", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateComponentMap")
    @ResponseWrapper(localName = "createComponentMapResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateComponentMapResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createComponentMapRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createComponentMapResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createComponentMap/Fault/CovRemoteServiceException")
    })
    public void createComponentMap(
            @WebParam(name = "componentMapSpec", targetNamespace = "")
            ComponentMapSpecDataObj componentMapSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamId
     * @param streamSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateStream", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateStream")
    @ResponseWrapper(localName = "updateStreamResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateStreamResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateStreamRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateStream/Fault/CovRemoteServiceException")
    })
    public void updateStream(
            @WebParam(name = "streamId", targetNamespace = "")
            StreamIdDataObj streamId,
            @WebParam(name = "streamSpec", targetNamespace = "")
            StreamSpecDataObj streamSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamId
     * @param onlyIfEmpty
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteStream", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteStream")
    @ResponseWrapper(localName = "deleteStreamResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteStreamResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteStreamRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteStream/Fault/CovRemoteServiceException")
    })
    public void deleteStream(
            @WebParam(name = "streamId", targetNamespace = "")
            StreamIdDataObj streamId,
            @WebParam(name = "onlyIfEmpty", targetNamespace = "")
            boolean onlyIfEmpty)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param triageStoreSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createTriageStore", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateTriageStore")
    @ResponseWrapper(localName = "createTriageStoreResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateTriageStoreResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createTriageStoreRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createTriageStoreResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createTriageStore/Fault/CovRemoteServiceException")
    })
    public void createTriageStore(
            @WebParam(name = "triageStoreSpec", targetNamespace = "")
            TriageStoreSpecDataObj triageStoreSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param triageStoreSpec
     * @param triageStoreId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateTriageStore", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateTriageStore")
    @ResponseWrapper(localName = "updateTriageStoreResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateTriageStoreResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateTriageStoreRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateTriageStoreResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateTriageStore/Fault/CovRemoteServiceException")
    })
    public void updateTriageStore(
            @WebParam(name = "triageStoreId", targetNamespace = "")
            TriageStoreIdDataObj triageStoreId,
            @WebParam(name = "triageStoreSpec", targetNamespace = "")
            TriageStoreSpecDataObj triageStoreSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param triageStoreId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteTriageStore", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteTriageStore")
    @ResponseWrapper(localName = "deleteTriageStoreResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteTriageStoreResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteTriageStoreRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteTriageStoreResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteTriageStore/Fault/CovRemoteServiceException")
    })
    public void deleteTriageStore(
            @WebParam(name = "triageStoreId", targetNamespace = "")
            TriageStoreIdDataObj triageStoreId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param userSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createUser", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateUserResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createUserRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createUserResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createUser/Fault/CovRemoteServiceException")
    })
    public void createUser(
            @WebParam(name = "userSpec", targetNamespace = "")
            UserSpecDataObj userSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param username
     * @param userSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateUserResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateUserRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateUserResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateUser/Fault/CovRemoteServiceException")
    })
    public void updateUser(
            @WebParam(name = "username", targetNamespace = "")
            String username,
            @WebParam(name = "userSpec", targetNamespace = "")
            UserSpecDataObj userSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param username
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteUserResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteUserRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteUserResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteUser/Fault/CovRemoteServiceException")
    })
    public void deleteUser(
            @WebParam(name = "username", targetNamespace = "")
            String username)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param username
     * @return
     *     returns com.coverity.ws.v9.UserDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetUserResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getUserRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getUserResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getUser/Fault/CovRemoteServiceException")
    })
    public UserDataObj getUser(
            @WebParam(name = "username", targetNamespace = "")
            String username)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v9.StreamDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStreams", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetStreams")
    @ResponseWrapper(localName = "getStreamsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetStreamsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getStreamsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getStreamsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getStreams/Fault/CovRemoteServiceException")
    })
    public List<StreamDataObj> getStreams(
            @WebParam(name = "filterSpec", targetNamespace = "")
            StreamFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param srcTriageStoreIds
     * @param triageStoreId
     * @param deleteSourceStores
     * @param assignStreamsToTargetStore
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "mergeTriageStores", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.MergeTriageStores")
    @ResponseWrapper(localName = "mergeTriageStoresResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.MergeTriageStoresResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/mergeTriageStoresRequest", output = "http://ws.coverity.com/v9/ConfigurationService/mergeTriageStoresResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/mergeTriageStores/Fault/CovRemoteServiceException")
    })
    public void mergeTriageStores(
            @WebParam(name = "srcTriageStoreIds", targetNamespace = "")
            List<TriageStoreIdDataObj> srcTriageStoreIds,
            @WebParam(name = "triageStoreId", targetNamespace = "")
            TriageStoreIdDataObj triageStoreId,
            @WebParam(name = "deleteSourceStores", targetNamespace = "")
            boolean deleteSourceStores,
            @WebParam(name = "assignStreamsToTargetStore", targetNamespace = "")
            boolean assignStreamsToTargetStore)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v9.PermissionDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPermissions", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetAllPermissions")
    @ResponseWrapper(localName = "getAllPermissionsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetAllPermissionsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getAllPermissionsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getAllPermissionsResponse")
    public List<PermissionDataObj> getAllPermissions();

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v9.LdapConfigurationDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllLdapConfigurations", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetAllLdapConfigurations")
    @ResponseWrapper(localName = "getAllLdapConfigurationsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetAllLdapConfigurationsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getAllLdapConfigurationsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getAllLdapConfigurationsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getAllLdapConfigurations/Fault/CovRemoteServiceException")
    })
    public List<LdapConfigurationDataObj> getAllLdapConfigurations()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param snapshotId
     * @return
     *     returns java.util.List<com.coverity.ws.v9.DeleteSnapshotJobInfoDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeleteSnapshotJobInfo", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetDeleteSnapshotJobInfo")
    @ResponseWrapper(localName = "getDeleteSnapshotJobInfoResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetDeleteSnapshotJobInfoResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getDeleteSnapshotJobInfoRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getDeleteSnapshotJobInfoResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getDeleteSnapshotJobInfo/Fault/CovRemoteServiceException")
    })
    public List<DeleteSnapshotJobInfoDataObj> getDeleteSnapshotJobInfo(
            @WebParam(name = "snapshotId", targetNamespace = "")
            List<SnapshotIdDataObj> snapshotId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamId
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v9.SnapshotIdDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSnapshotsForStream", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetSnapshotsForStream")
    @ResponseWrapper(localName = "getSnapshotsForStreamResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetSnapshotsForStreamResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getSnapshotsForStreamRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getSnapshotsForStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getSnapshotsForStream/Fault/CovRemoteServiceException")
    })
    public List<SnapshotIdDataObj> getSnapshotsForStream(
            @WebParam(name = "streamId", targetNamespace = "")
            StreamIdDataObj streamId,
            @WebParam(name = "filterSpec", targetNamespace = "")
            SnapshotFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param serverDomainIdDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteLdapConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteLdapConfiguration")
    @ResponseWrapper(localName = "deleteLdapConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteLdapConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteLdapConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteLdapConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteLdapConfiguration/Fault/CovRemoteServiceException")
    })
    public void deleteLdapConfiguration(
            @WebParam(name = "serverDomainIdDataObj", targetNamespace = "")
            ServerDomainIdDataObj serverDomainIdDataObj)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v9.FeatureUpdateTimeDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastUpdateTimes", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetLastUpdateTimes")
    @ResponseWrapper(localName = "getLastUpdateTimesResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetLastUpdateTimesResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getLastUpdateTimesRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getLastUpdateTimesResponse")
    public List<FeatureUpdateTimeDataObj> getLastUpdateTimes();

    /**
     * 
     * @param acceptNewCommits
     */
    @WebMethod
    @RequestWrapper(localName = "setAcceptingNewCommits", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.SetAcceptingNewCommits")
    @ResponseWrapper(localName = "setAcceptingNewCommitsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.SetAcceptingNewCommitsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/setAcceptingNewCommitsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/setAcceptingNewCommitsResponse")
    public void setAcceptingNewCommits(
            @WebParam(name = "acceptNewCommits", targetNamespace = "")
            boolean acceptNewCommits);

    /**
     * 
     * @param snapshotId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteSnapshot", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteSnapshot")
    @ResponseWrapper(localName = "deleteSnapshotResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.DeleteSnapshotResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/deleteSnapshotRequest", output = "http://ws.coverity.com/v9/ConfigurationService/deleteSnapshotResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/deleteSnapshot/Fault/CovRemoteServiceException")
    })
    public void deleteSnapshot(
            @WebParam(name = "snapshotId", targetNamespace = "")
            List<SnapshotIdDataObj> snapshotId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param viewname
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "executeNotification", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.ExecuteNotification")
    @ResponseWrapper(localName = "executeNotificationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.ExecuteNotificationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/executeNotificationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/executeNotificationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/executeNotification/Fault/CovRemoteServiceException")
    })
    public void executeNotification(
            @WebParam(name = "viewname", targetNamespace = "")
            String viewname)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectId
     * @param sourceStreamId
     * @return
     *     returns com.coverity.ws.v9.StreamDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "copyStream", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CopyStream")
    @ResponseWrapper(localName = "copyStreamResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CopyStreamResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/copyStreamRequest", output = "http://ws.coverity.com/v9/ConfigurationService/copyStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/copyStream/Fault/CovRemoteServiceException")
    })
    public StreamDataObj copyStream(
            @WebParam(name = "projectId", targetNamespace = "")
            ProjectIdDataObj projectId,
            @WebParam(name = "sourceStreamId", targetNamespace = "")
            StreamIdDataObj sourceStreamId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamSpec
     * @param projectId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createStreamInProject", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateStreamInProject")
    @ResponseWrapper(localName = "createStreamInProjectResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateStreamInProjectResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createStreamInProjectRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createStreamInProjectResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createStreamInProject/Fault/CovRemoteServiceException")
    })
    public void createStreamInProject(
            @WebParam(name = "projectId", targetNamespace = "")
            ProjectIdDataObj projectId,
            @WebParam(name = "streamSpec", targetNamespace = "")
            StreamSpecDataObj streamSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMessageOfTheDay", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetMessageOfTheDay")
    @ResponseWrapper(localName = "getMessageOfTheDayResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetMessageOfTheDayResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getMessageOfTheDayRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getMessageOfTheDayResponse")
    public String getMessageOfTheDay();

    /**
     * 
     * @param message
     */
    @WebMethod
    @RequestWrapper(localName = "setMessageOfTheDay", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.SetMessageOfTheDay")
    @ResponseWrapper(localName = "setMessageOfTheDayResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.SetMessageOfTheDayResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/setMessageOfTheDayRequest", output = "http://ws.coverity.com/v9/ConfigurationService/setMessageOfTheDayResponse")
    public void setMessageOfTheDay(
            @WebParam(name = "message", targetNamespace = "")
            String message);

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v9.ProjectDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProjects", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetProjects")
    @ResponseWrapper(localName = "getProjectsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetProjectsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getProjectsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getProjectsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getProjects/Fault/CovRemoteServiceException")
    })
    public List<ProjectDataObj> getProjects(
            @WebParam(name = "filterSpec", targetNamespace = "")
            ProjectFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v9.ComponentMapDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComponentMaps", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetComponentMaps")
    @ResponseWrapper(localName = "getComponentMapsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetComponentMapsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getComponentMapsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getComponentMapsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getComponentMaps/Fault/CovRemoteServiceException")
    })
    public List<ComponentMapDataObj> getComponentMaps(
            @WebParam(name = "filterSpec", targetNamespace = "")
            ComponentMapFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v9.TriageStoreDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTriageStores", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetTriageStores")
    @ResponseWrapper(localName = "getTriageStoresResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetTriageStoresResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getTriageStoresRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getTriageStoresResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getTriageStores/Fault/CovRemoteServiceException")
    })
    public List<TriageStoreDataObj> getTriageStores(
            @WebParam(name = "filterSpec", targetNamespace = "")
            TriageStoreFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v9.LocalizedValueDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTypeNames", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetTypeNames")
    @ResponseWrapper(localName = "getTypeNamesResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetTypeNamesResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getTypeNamesRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getTypeNamesResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getTypeNames/Fault/CovRemoteServiceException")
    })
    public List<LocalizedValueDataObj> getTypeNames()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDefectStatuses", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetDefectStatuses")
    @ResponseWrapper(localName = "getDefectStatusesResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetDefectStatusesResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getDefectStatusesRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getDefectStatusesResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getDefectStatuses/Fault/CovRemoteServiceException")
    })
    public List<String> getDefectStatuses()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param snapshotIds
     * @return
     *     returns java.util.List<com.coverity.ws.v9.SnapshotInfoDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSnapshotInformation", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetSnapshotInformation")
    @ResponseWrapper(localName = "getSnapshotInformationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetSnapshotInformationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getSnapshotInformationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getSnapshotInformationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getSnapshotInformation/Fault/CovRemoteServiceException")
    })
    public List<SnapshotInfoDataObj> getSnapshotInformation(
            @WebParam(name = "snapshotIds", targetNamespace = "")
            List<SnapshotIdDataObj> snapshotIds)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param snapshotId
     * @param snapshotData
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateSnapshotInfo", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateSnapshotInfo")
    @ResponseWrapper(localName = "updateSnapshotInfoResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateSnapshotInfoResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateSnapshotInfoRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateSnapshotInfoResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateSnapshotInfo/Fault/CovRemoteServiceException")
    })
    public void updateSnapshotInfo(
            @WebParam(name = "snapshotId", targetNamespace = "")
            SnapshotIdDataObj snapshotId,
            @WebParam(name = "snapshotData", targetNamespace = "")
            SnapshotInfoDataObj snapshotData)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v9.CommitStateDataObj
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCommitState", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetCommitState")
    @ResponseWrapper(localName = "getCommitStateResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetCommitStateResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getCommitStateRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getCommitStateResponse")
    public CommitStateDataObj getCommitState();

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v9.ServerDomainIdDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLdapServerDomains", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetLdapServerDomains")
    @ResponseWrapper(localName = "getLdapServerDomainsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetLdapServerDomainsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getLdapServerDomainsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getLdapServerDomainsResponse")
    public List<ServerDomainIdDataObj> getLdapServerDomains();

    /**
     * 
     * @param licenseSpecDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "importLicense", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.ImportLicense")
    @ResponseWrapper(localName = "importLicenseResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.ImportLicenseResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/importLicenseRequest", output = "http://ws.coverity.com/v9/ConfigurationService/importLicenseResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/importLicense/Fault/CovRemoteServiceException")
    })
    public void importLicense(
            @WebParam(name = "licenseSpecDataObj", targetNamespace = "")
            LicenseSpecDataObj licenseSpecDataObj)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServerTime", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetServerTime")
    @ResponseWrapper(localName = "getServerTimeResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetServerTimeResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getServerTimeRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getServerTimeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getServerTime/Fault/CovRemoteServiceException")
    })
    public XMLGregorianCalendar getServerTime()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v9.ConfigurationDataObj
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSystemConfig", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetSystemConfig")
    @ResponseWrapper(localName = "getSystemConfigResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetSystemConfigResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getSystemConfigRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getSystemConfigResponse")
    public ConfigurationDataObj getSystemConfig();

    /**
     * 
     * @return
     *     returns com.coverity.ws.v9.LicenseStateDataObj
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLicenseState", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetLicenseState")
    @ResponseWrapper(localName = "getLicenseStateResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetLicenseStateResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getLicenseStateRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getLicenseStateResponse")
    public LicenseStateDataObj getLicenseState();

    /**
     * 
     * @param backupConfigurationDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setBackupConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.SetBackupConfiguration")
    @ResponseWrapper(localName = "setBackupConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.SetBackupConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/setBackupConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/setBackupConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/setBackupConfiguration/Fault/CovRemoteServiceException")
    })
    public void setBackupConfiguration(
            @WebParam(name = "backupConfigurationDataObj", targetNamespace = "")
            BackupConfigurationDataObj backupConfigurationDataObj)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param purgeDetailsSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setSnapshotPurgeDetails", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.SetSnapshotPurgeDetails")
    @ResponseWrapper(localName = "setSnapshotPurgeDetailsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.SetSnapshotPurgeDetailsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/setSnapshotPurgeDetailsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/setSnapshotPurgeDetailsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/setSnapshotPurgeDetails/Fault/CovRemoteServiceException")
    })
    public void setSnapshotPurgeDetails(
            @WebParam(name = "purgeDetailsSpec", targetNamespace = "")
            SnapshotPurgeDetailsObj purgeDetailsSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param ldapConfigurationSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createLdapConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateLdapConfiguration")
    @ResponseWrapper(localName = "createLdapConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateLdapConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createLdapConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createLdapConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createLdapConfiguration/Fault/CovRemoteServiceException")
    })
    public void createLdapConfiguration(
            @WebParam(name = "ldapConfigurationSpec", targetNamespace = "")
            LdapConfigurationSpecDataObj ldapConfigurationSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param ldapConfigurationSpec
     * @param serverDomainIdDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateLdapConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateLdapConfiguration")
    @ResponseWrapper(localName = "updateLdapConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateLdapConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateLdapConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateLdapConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateLdapConfiguration/Fault/CovRemoteServiceException")
    })
    public void updateLdapConfiguration(
            @WebParam(name = "serverDomainIdDataObj", targetNamespace = "")
            ServerDomainIdDataObj serverDomainIdDataObj,
            @WebParam(name = "ldapConfigurationSpec", targetNamespace = "")
            LdapConfigurationSpecDataObj ldapConfigurationSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v9.SnapshotPurgeDetailsObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSnapshotPurgeDetails", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetSnapshotPurgeDetails")
    @ResponseWrapper(localName = "getSnapshotPurgeDetailsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetSnapshotPurgeDetailsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getSnapshotPurgeDetailsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getSnapshotPurgeDetailsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getSnapshotPurgeDetails/Fault/CovRemoteServiceException")
    })
    public SnapshotPurgeDetailsObj getSnapshotPurgeDetails()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param signInSettingsDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateSignInConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateSignInConfiguration")
    @ResponseWrapper(localName = "updateSignInConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.UpdateSignInConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/updateSignInConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/updateSignInConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/updateSignInConfiguration/Fault/CovRemoteServiceException")
    })
    public void updateSignInConfiguration(
            @WebParam(name = "signInSettingsDataObj", targetNamespace = "")
            SignInSettingsDataObj signInSettingsDataObj)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param skeletonizationConfigurationDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setSkeletonizationConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.SetSkeletonizationConfiguration")
    @ResponseWrapper(localName = "setSkeletonizationConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.SetSkeletonizationConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/setSkeletonizationConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/setSkeletonizationConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/setSkeletonizationConfiguration/Fault/CovRemoteServiceException")
    })
    public void setSkeletonizationConfiguration(
            @WebParam(name = "skeletonizationConfigurationDataObj", targetNamespace = "")
            SkeletonizationConfigurationDataObj skeletonizationConfigurationDataObj)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v9.LoggingConfigurationDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLoggingConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetLoggingConfiguration")
    @ResponseWrapper(localName = "getLoggingConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetLoggingConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getLoggingConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getLoggingConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getLoggingConfiguration/Fault/CovRemoteServiceException")
    })
    public LoggingConfigurationDataObj getLoggingConfiguration()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v9.LicenseDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLicenseConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetLicenseConfiguration")
    @ResponseWrapper(localName = "getLicenseConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetLicenseConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getLicenseConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getLicenseConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getLicenseConfiguration/Fault/CovRemoteServiceException")
    })
    public LicenseDataObj getLicenseConfiguration()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param loggingConfigurationDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setLoggingConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.SetLoggingConfiguration")
    @ResponseWrapper(localName = "setLoggingConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.SetLoggingConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/setLoggingConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/setLoggingConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/setLoggingConfiguration/Fault/CovRemoteServiceException")
    })
    public void setLoggingConfiguration(
            @WebParam(name = "loggingConfigurationDataObj", targetNamespace = "")
            LoggingConfigurationDataObj loggingConfigurationDataObj)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v9.ProjectDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeveloperStreamsProjects", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetDeveloperStreamsProjects")
    @ResponseWrapper(localName = "getDeveloperStreamsProjectsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetDeveloperStreamsProjectsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getDeveloperStreamsProjectsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getDeveloperStreamsProjectsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getDeveloperStreamsProjects/Fault/CovRemoteServiceException")
    })
    public List<ProjectDataObj> getDeveloperStreamsProjects(
            @WebParam(name = "filterSpec", targetNamespace = "")
            ProjectFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v9.SignInSettingsDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSignInConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetSignInConfiguration")
    @ResponseWrapper(localName = "getSignInConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetSignInConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getSignInConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getSignInConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getSignInConfiguration/Fault/CovRemoteServiceException")
    })
    public SignInSettingsDataObj getSignInConfiguration()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v9.BackupConfigurationDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBackupConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetBackupConfiguration")
    @ResponseWrapper(localName = "getBackupConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetBackupConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getBackupConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getBackupConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getBackupConfiguration/Fault/CovRemoteServiceException")
    })
    public BackupConfigurationDataObj getBackupConfiguration()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v9.SkeletonizationConfigurationDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSkeletonizationConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetSkeletonizationConfiguration")
    @ResponseWrapper(localName = "getSkeletonizationConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetSkeletonizationConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getSkeletonizationConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getSkeletonizationConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getSkeletonizationConfiguration/Fault/CovRemoteServiceException")
    })
    public SkeletonizationConfigurationDataObj getSkeletonizationConfiguration()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getArchitectureAnalysisConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetArchitectureAnalysisConfiguration")
    @ResponseWrapper(localName = "getArchitectureAnalysisConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetArchitectureAnalysisConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getArchitectureAnalysisConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getArchitectureAnalysisConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getArchitectureAnalysisConfiguration/Fault/CovRemoteServiceException")
    })
    public String getArchitectureAnalysisConfiguration()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param architectureAnalysisConfiguration
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setArchitectureAnalysisConfiguration", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.SetArchitectureAnalysisConfiguration")
    @ResponseWrapper(localName = "setArchitectureAnalysisConfigurationResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.SetArchitectureAnalysisConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/setArchitectureAnalysisConfigurationRequest", output = "http://ws.coverity.com/v9/ConfigurationService/setArchitectureAnalysisConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/setArchitectureAnalysisConfiguration/Fault/CovRemoteServiceException")
    })
    public void setArchitectureAnalysisConfiguration(
            @WebParam(name = "architectureAnalysisConfiguration", targetNamespace = "")
            String architectureAnalysisConfiguration)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v9.LocalizedValueDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCategoryNames", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetCategoryNames")
    @ResponseWrapper(localName = "getCategoryNamesResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetCategoryNamesResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getCategoryNamesRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getCategoryNamesResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getCategoryNames/Fault/CovRemoteServiceException")
    })
    public List<LocalizedValueDataObj> getCategoryNames()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCheckerNames", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetCheckerNames")
    @ResponseWrapper(localName = "getCheckerNamesResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetCheckerNamesResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getCheckerNamesRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getCheckerNamesResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getCheckerNames/Fault/CovRemoteServiceException")
    })
    public List<String> getCheckerNames()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v9.VersionDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetVersionResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getVersionRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getVersionResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getVersion/Fault/CovRemoteServiceException")
    })
    public VersionDataObj getVersion()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param groupSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createGroup", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateGroup")
    @ResponseWrapper(localName = "createGroupResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateGroupResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createGroupRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createGroupResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createGroup/Fault/CovRemoteServiceException")
    })
    public void createGroup(
            @WebParam(name = "groupSpec", targetNamespace = "")
            GroupSpecDataObj groupSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param message
     * @param usernames
     * @param subject
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "notify", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.Notify")
    @ResponseWrapper(localName = "notifyResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.NotifyResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/notifyRequest", output = "http://ws.coverity.com/v9/ConfigurationService/notifyResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/notify/Fault/CovRemoteServiceException")
    })
    public List<String> notify(
            @WebParam(name = "usernames", targetNamespace = "")
            List<String> usernames,
            @WebParam(name = "subject", targetNamespace = "")
            String subject,
            @WebParam(name = "message", targetNamespace = "")
            String message)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v9.AttributeDefinitionDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAttributes", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetAttributes")
    @ResponseWrapper(localName = "getAttributesResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetAttributesResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getAttributesRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getAttributesResponse")
    public List<AttributeDefinitionDataObj> getAttributes();

    /**
     * 
     * @param attributeDefinitionId
     * @return
     *     returns com.coverity.ws.v9.AttributeDefinitionDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAttribute", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetAttribute")
    @ResponseWrapper(localName = "getAttributeResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetAttributeResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getAttributeRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getAttributeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getAttribute/Fault/CovRemoteServiceException")
    })
    public AttributeDefinitionDataObj getAttribute(
            @WebParam(name = "attributeDefinitionId", targetNamespace = "")
            AttributeDefinitionIdDataObj attributeDefinitionId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentId
     * @return
     *     returns com.coverity.ws.v9.ComponentDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComponent", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetComponent")
    @ResponseWrapper(localName = "getComponentResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetComponentResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getComponentRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getComponentResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getComponent/Fault/CovRemoteServiceException")
    })
    public ComponentDataObj getComponent(
            @WebParam(name = "componentId", targetNamespace = "")
            ComponentIdDataObj componentId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param attributeDefinitionSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createAttribute", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateAttribute")
    @ResponseWrapper(localName = "createAttributeResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.CreateAttributeResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/createAttributeRequest", output = "http://ws.coverity.com/v9/ConfigurationService/createAttributeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/createAttribute/Fault/CovRemoteServiceException")
    })
    public void createAttribute(
            @WebParam(name = "attributeDefinitionSpec", targetNamespace = "")
            AttributeDefinitionSpecDataObj attributeDefinitionSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @param pageSpec
     * @return
     *     returns com.coverity.ws.v9.GroupsPageDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGroups", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetGroups")
    @ResponseWrapper(localName = "getGroupsResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetGroupsResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getGroupsRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getGroupsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getGroups/Fault/CovRemoteServiceException")
    })
    public GroupsPageDataObj getGroups(
            @WebParam(name = "filterSpec", targetNamespace = "")
            GroupFilterSpecDataObj filterSpec,
            @WebParam(name = "pageSpec", targetNamespace = "")
            PageSpecDataObj pageSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @param pageSpec
     * @return
     *     returns com.coverity.ws.v9.UsersPageDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetUsersResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getUsersRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getUsersResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getUsers/Fault/CovRemoteServiceException")
    })
    public UsersPageDataObj getUsers(
            @WebParam(name = "filterSpec", targetNamespace = "")
            UserFilterSpecDataObj filterSpec,
            @WebParam(name = "pageSpec", targetNamespace = "")
            PageSpecDataObj pageSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param roleId
     * @return
     *     returns com.coverity.ws.v9.RoleDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRole", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetRole")
    @ResponseWrapper(localName = "getRoleResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetRoleResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getRoleRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getRoleResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getRole/Fault/CovRemoteServiceException")
    })
    public RoleDataObj getRole(
            @WebParam(name = "roleId", targetNamespace = "")
            RoleIdDataObj roleId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param groupId
     * @return
     *     returns com.coverity.ws.v9.GroupDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGroup", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetGroup")
    @ResponseWrapper(localName = "getGroupResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetGroupResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getGroupRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getGroupResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v9/ConfigurationService/getGroup/Fault/CovRemoteServiceException")
    })
    public GroupDataObj getGroup(
            @WebParam(name = "groupId", targetNamespace = "")
            GroupIdDataObj groupId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v9.RoleDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllRoles", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetAllRoles")
    @ResponseWrapper(localName = "getAllRolesResponse", targetNamespace = "http://ws.coverity.com/v9", className = "com.coverity.ws.v9.GetAllRolesResponse")
    @Action(input = "http://ws.coverity.com/v9/ConfigurationService/getAllRolesRequest", output = "http://ws.coverity.com/v9/ConfigurationService/getAllRolesResponse")
    public List<RoleDataObj> getAllRoles();

}
