package com.coverity.ws.v3;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ConfigurationService", targetNamespace = "http://ws.coverity.com/v3")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConfigurationService {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActions", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetActions")
    @ResponseWrapper(localName = "getActionsResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetActionsResponse")
    public List<String> getActions();

    /**
     * 
     * @param componentMapId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteComponentMap", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.DeleteComponentMap")
    @ResponseWrapper(localName = "deleteComponentMapResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.DeleteComponentMapResponse")
    public void deleteComponentMap(
            @WebParam(name = "componentMapId", targetNamespace = "")
            ComponentMapIdDataObj componentMapId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentMapFilter
     * @return
     *     returns com.coverity.ws.v3.ComponentDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComponent", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetComponent")
    @ResponseWrapper(localName = "getComponentResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetComponentResponse")
    public ComponentDataObj getComponent(
            @WebParam(name = "componentMapFilter", targetNamespace = "")
            ComponentIdDataObj componentMapFilter)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteStream", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.DeleteStream")
    @ResponseWrapper(localName = "deleteStreamResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.DeleteStreamResponse")
    public void deleteStream(
            @WebParam(name = "streamId", targetNamespace = "")
            StreamIdDataObj streamId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param snapshotId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteSnapshot", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.DeleteSnapshot")
    @ResponseWrapper(localName = "deleteSnapshotResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.DeleteSnapshotResponse")
    public void deleteSnapshot(
            @WebParam(name = "snapshotId", targetNamespace = "")
            SnapshotIdDataObj snapshotId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v3.StreamDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStreams", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetStreams")
    @ResponseWrapper(localName = "getStreamsResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetStreamsResponse")
    public List<StreamDataObj> getStreams(
            @WebParam(name = "filterSpec", targetNamespace = "")
            StreamFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createProject", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.CreateProject")
    @ResponseWrapper(localName = "createProjectResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.CreateProjectResponse")
    public void createProject(
            @WebParam(name = "projectSpec", targetNamespace = "")
            ProjectSpecDataObj projectSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v3.ProjectDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProjects", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetProjects")
    @ResponseWrapper(localName = "getProjectsResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetProjectsResponse")
    public List<ProjectDataObj> getProjects(
            @WebParam(name = "filterSpec", targetNamespace = "")
            ProjectFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectSpec
     * @param projectId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateProject", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.UpdateProject")
    @ResponseWrapper(localName = "updateProjectResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.UpdateProjectResponse")
    public void updateProject(
            @WebParam(name = "projectId", targetNamespace = "")
            ProjectIdDataObj projectId,
            @WebParam(name = "projectSpec", targetNamespace = "")
            ProjectSpecDataObj projectSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteProject", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.DeleteProject")
    @ResponseWrapper(localName = "deleteProjectResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.DeleteProjectResponse")
    public void deleteProject(
            @WebParam(name = "projectId", targetNamespace = "")
            ProjectIdDataObj projectId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createStream", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.CreateStream")
    @ResponseWrapper(localName = "createStreamResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.CreateStreamResponse")
    public void createStream(
            @WebParam(name = "streamSpec", targetNamespace = "")
            StreamSpecDataObj streamSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamId
     * @param streamSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateStream", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.UpdateStream")
    @ResponseWrapper(localName = "updateStreamResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.UpdateStreamResponse")
    public void updateStream(
            @WebParam(name = "streamId", targetNamespace = "")
            StreamIdDataObj streamId,
            @WebParam(name = "streamSpec", targetNamespace = "")
            StreamSpecDataObj streamSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDefectStatuses", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetDefectStatuses")
    @ResponseWrapper(localName = "getDefectStatusesResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetDefectStatusesResponse")
    public List<String> getDefectStatuses();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClassifications", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetClassifications")
    @ResponseWrapper(localName = "getClassificationsResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetClassificationsResponse")
    public List<String> getClassifications();

    /**
     * 
     * @param actions
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateActions", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.UpdateActions")
    @ResponseWrapper(localName = "updateActionsResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.UpdateActionsResponse")
    public void updateActions(
            @WebParam(name = "actions", targetNamespace = "")
            List<String> actions)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSeverities", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetSeverities")
    @ResponseWrapper(localName = "getSeveritiesResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetSeveritiesResponse")
    public List<String> getSeverities();

    /**
     * 
     * @param severities
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateSeverities", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.UpdateSeverities")
    @ResponseWrapper(localName = "updateSeveritiesResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.UpdateSeveritiesResponse")
    public void updateSeverities(
            @WebParam(name = "severities", targetNamespace = "")
            List<String> severities)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentMapSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createComponentMap", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.CreateComponentMap")
    @ResponseWrapper(localName = "createComponentMapResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.CreateComponentMapResponse")
    public void createComponentMap(
            @WebParam(name = "componentMapSpec", targetNamespace = "")
            ComponentMapSpecDataObj componentMapSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentMapId
     * @return
     *     returns java.util.List<com.coverity.ws.v3.ComponentMapDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComponentMaps", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetComponentMaps")
    @ResponseWrapper(localName = "getComponentMapsResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetComponentMapsResponse")
    public List<ComponentMapDataObj> getComponentMaps(
            @WebParam(name = "componentMapId", targetNamespace = "")
            ComponentMapFilterSpecDataObj componentMapId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentMapSpec
     * @param componentMapFilter
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateComponentMap", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.UpdateComponentMap")
    @ResponseWrapper(localName = "updateComponentMapResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.UpdateComponentMapResponse")
    public void updateComponentMap(
            @WebParam(name = "componentMapFilter", targetNamespace = "")
            ComponentMapIdDataObj componentMapFilter,
            @WebParam(name = "componentMapSpec", targetNamespace = "")
            ComponentMapSpecDataObj componentMapSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamId
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v3.SnapshotInfoDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSnapshotsForStream", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetSnapshotsForStream")
    @ResponseWrapper(localName = "getSnapshotsForStreamResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetSnapshotsForStreamResponse")
    public List<SnapshotInfoDataObj> getSnapshotsForStream(
            @WebParam(name = "streamId", targetNamespace = "")
            StreamIdDataObj streamId,
            @WebParam(name = "filterSpec", targetNamespace = "")
            SnapshotFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

}
