package com.coverity.ws.v3;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DefectService", targetNamespace = "http://ws.coverity.com/v3")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DefectService {


    /**
     * 
     * @param properties
     * @param defectInstanceId
     * @throws com.coverity.ws.v3.CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateDefectInstanceProperties", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.UpdateDefectInstanceProperties")
    @ResponseWrapper(localName = "updateDefectInstancePropertiesResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.UpdateDefectInstancePropertiesResponse")
    public void updateDefectInstanceProperties(
            @WebParam(name = "defectInstanceId", targetNamespace = "")
            DefectInstanceIdDataObj defectInstanceId,
            @WebParam(name = "properties", targetNamespace = "")
            List<PropertySpecDataObj> properties)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamDefectIds
     * @param defectStateSpec
     * @throws com.coverity.ws.v3.CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateStreamDefects", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.UpdateStreamDefects")
    @ResponseWrapper(localName = "updateStreamDefectsResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.UpdateStreamDefectsResponse")
    public void updateStreamDefects(
            @WebParam(name = "streamDefectIds", targetNamespace = "")
            List<StreamDefectIdDataObj> streamDefectIds,
            @WebParam(name = "defectStateSpec", targetNamespace = "")
            DefectStateSpecDataObj defectStateSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @param cids
     * @return
     *     returns java.util.List<com.coverity.ws.v3.StreamDefectDataObj>
     * @throws com.coverity.ws.v3.CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStreamDefects", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetStreamDefects")
    @ResponseWrapper(localName = "getStreamDefectsResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetStreamDefectsResponse")
    public List<StreamDefectDataObj> getStreamDefects(
            @WebParam(name = "cids", targetNamespace = "")
            List<Long> cids,
            @WebParam(name = "filterSpec", targetNamespace = "")
            StreamDefectFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @param projectId
     * @param pageSpec
     * @return
     *     returns com.coverity.ws.v3.MergedDefectsPageDataObj
     * @throws com.coverity.ws.v3.CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMergedDefectsForProject", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetMergedDefectsForProject")
    @ResponseWrapper(localName = "getMergedDefectsForProjectResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetMergedDefectsForProjectResponse")
    public MergedDefectsPageDataObj getMergedDefectsForProject(
            @WebParam(name = "projectId", targetNamespace = "")
            ProjectIdDataObj projectId,
            @WebParam(name = "filterSpec", targetNamespace = "")
            MergedDefectFilterSpecDataObj filterSpec,
            @WebParam(name = "pageSpec", targetNamespace = "")
            PageSpecDataObj pageSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param analysisStreamIds
     * @param filterSpec
     * @param pageSpec
     * @return
     *     returns com.coverity.ws.v3.MergedDefectsPageDataObj
     * @throws com.coverity.ws.v3.CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMergedDefectsForStreams", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetMergedDefectsForStreams")
    @ResponseWrapper(localName = "getMergedDefectsForStreamsResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetMergedDefectsForStreamsResponse")
    public MergedDefectsPageDataObj getMergedDefectsForStreams(
            @WebParam(name = "analysisStreamIds", targetNamespace = "")
            List<StreamIdDataObj> analysisStreamIds,
            @WebParam(name = "filterSpec", targetNamespace = "")
            MergedDefectFilterSpecDataObj filterSpec,
            @WebParam(name = "pageSpec", targetNamespace = "")
            PageSpecDataObj pageSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param scopePattern
     * @param cid
     * @return
     *     returns java.util.List<com.coverity.ws.v3.DefectChangeDataObj>
     * @throws com.coverity.ws.v3.CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMergedDefectHistory", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetMergedDefectHistory")
    @ResponseWrapper(localName = "getMergedDefectHistoryResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetMergedDefectHistoryResponse")
    public List<DefectChangeDataObj> getMergedDefectHistory(
            @WebParam(name = "cid", targetNamespace = "")
            Long cid,
            @WebParam(name = "scopePattern", targetNamespace = "")
            String scopePattern)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @param projectId
     * @return
     *     returns java.util.List<com.coverity.ws.v3.ProjectMetricsDataObj>
     * @throws com.coverity.ws.v3.CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTrendRecordsForProject", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetTrendRecordsForProject")
    @ResponseWrapper(localName = "getTrendRecordsForProjectResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetTrendRecordsForProjectResponse")
    public List<ProjectMetricsDataObj> getTrendRecordsForProject(
            @WebParam(name = "projectId", targetNamespace = "")
            ProjectIdDataObj projectId,
            @WebParam(name = "filterSpec", targetNamespace = "")
            ProjectTrendRecordFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentIds
     * @param projectId
     * @return
     *     returns java.util.List<com.coverity.ws.v3.ComponentMetricsDataObj>
     * @throws com.coverity.ws.v3.CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComponentMetricsForProject", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetComponentMetricsForProject")
    @ResponseWrapper(localName = "getComponentMetricsForProjectResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetComponentMetricsForProjectResponse")
    public List<ComponentMetricsDataObj> getComponentMetricsForProject(
            @WebParam(name = "projectId", targetNamespace = "")
            ProjectIdDataObj projectId,
            @WebParam(name = "componentIds", targetNamespace = "")
            List<ComponentIdDataObj> componentIds)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @param projectId
     * @return
     *     returns java.util.List<java.lang.Long>
     * @throws com.coverity.ws.v3.CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCIDsForProject", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetCIDsForProject")
    @ResponseWrapper(localName = "getCIDsForProjectResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetCIDsForProjectResponse")
    public List<Long> getCIDsForProject(
            @WebParam(name = "projectId", targetNamespace = "")
            ProjectIdDataObj projectId,
            @WebParam(name = "filterSpec", targetNamespace = "")
            MergedDefectFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param analysisStreamIds
     * @param filterSpec
     * @return
     *     returns java.util.List<java.lang.Long>
     * @throws com.coverity.ws.v3.CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCIDsForStreams", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetCIDsForStreams")
    @ResponseWrapper(localName = "getCIDsForStreamsResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetCIDsForStreamsResponse")
    public List<Long> getCIDsForStreams(
            @WebParam(name = "analysisStreamIds", targetNamespace = "")
            List<StreamIdDataObj> analysisStreamIds,
            @WebParam(name = "filterSpec", targetNamespace = "")
            MergedDefectFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param dmCid
     * @param databaseDescription
     * @return
     *     returns java.lang.Long
     * @throws com.coverity.ws.v3.CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCIDForDMCID", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetCIDForDMCID")
    @ResponseWrapper(localName = "getCIDForDMCIDResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetCIDForDMCIDResponse")
    public Long getCIDForDMCID(
            @WebParam(name = "dmCid", targetNamespace = "")
            Long dmCid,
            @WebParam(name = "databaseDescription", targetNamespace = "")
            String databaseDescription)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param snapshotId
     * @return
     *     returns java.util.List<java.lang.Long>
     * @throws com.coverity.ws.v3.CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCIDsForSnapshot", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetCIDsForSnapshot")
    @ResponseWrapper(localName = "getCIDsForSnapshotResponse", targetNamespace = "http://ws.coverity.com/v3", className = "com.coverity.ws.v3.GetCIDsForSnapshotResponse")
    public List<Long> getCIDsForSnapshot(
            @WebParam(name = "snapshotId", targetNamespace = "")
            SnapshotIdDataObj snapshotId)
        throws CovRemoteServiceException_Exception
    ;

}
