
package com.coverity.ws.v6;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "CoverityFault", targetNamespace = "http://ws.coverity.com/v6")
public class CovRemoteServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CovRemoteServiceException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public CovRemoteServiceException_Exception(String message, CovRemoteServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public CovRemoteServiceException_Exception(String message, CovRemoteServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.coverity.ws.v6.CovRemoteServiceException
     */
    public CovRemoteServiceException getFaultInfo() {
        return faultInfo;
    }

}
