
package com.coverity.ws.v6;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DefectService", targetNamespace = "http://ws.coverity.com/v6")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DefectService {


    /**
     * 
     * @param streamDefectIds
     * @param defectStateSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateStreamDefects", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.UpdateStreamDefects")
    @ResponseWrapper(localName = "updateStreamDefectsResponse", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.UpdateStreamDefectsResponse")
    public void updateStreamDefects(
        @WebParam(name = "streamDefectIds", targetNamespace = "")
        List<StreamDefectIdDataObj> streamDefectIds,
        @WebParam(name = "defectStateSpec", targetNamespace = "")
        DefectStateSpecDataObj defectStateSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param dmCid
     * @param databaseDescription
     * @return
     *     returns java.lang.Long
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCIDForDMCID", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetCIDForDMCID")
    @ResponseWrapper(localName = "getCIDForDMCIDResponse", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetCIDForDMCIDResponse")
    public Long getCIDForDMCID(
        @WebParam(name = "dmCid", targetNamespace = "")
        Long dmCid,
        @WebParam(name = "databaseDescription", targetNamespace = "")
        String databaseDescription)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Long
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCIDForMergeKey", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetCIDForMergeKey")
    @ResponseWrapper(localName = "getCIDForMergeKeyResponse", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetCIDForMergeKeyResponse")
    public Long getCIDForMergeKey(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param properties
     * @param defectInstanceId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateDefectInstanceProperties", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.UpdateDefectInstanceProperties")
    @ResponseWrapper(localName = "updateDefectInstancePropertiesResponse", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.UpdateDefectInstancePropertiesResponse")
    public void updateDefectInstanceProperties(
        @WebParam(name = "defectInstanceId", targetNamespace = "")
        DefectInstanceIdDataObj defectInstanceId,
        @WebParam(name = "properties", targetNamespace = "")
        List<PropertySpecDataObj> properties)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @param cids
     * @return
     *     returns java.util.List<com.coverity.ws.v6.StreamDefectDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStreamDefects", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetStreamDefects")
    @ResponseWrapper(localName = "getStreamDefectsResponse", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetStreamDefectsResponse")
    public List<StreamDefectDataObj> getStreamDefects(
        @WebParam(name = "cids", targetNamespace = "")
        List<Long> cids,
        @WebParam(name = "filterSpec", targetNamespace = "")
        StreamDefectFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @param projectId
     * @param pageSpec
     * @return
     *     returns com.coverity.ws.v6.MergedDefectsPageDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMergedDefectsForProject", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetMergedDefectsForProject")
    @ResponseWrapper(localName = "getMergedDefectsForProjectResponse", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetMergedDefectsForProjectResponse")
    public MergedDefectsPageDataObj getMergedDefectsForProject(
        @WebParam(name = "projectId", targetNamespace = "")
        ProjectIdDataObj projectId,
        @WebParam(name = "filterSpec", targetNamespace = "")
        MergedDefectFilterSpecDataObj filterSpec,
        @WebParam(name = "pageSpec", targetNamespace = "")
        PageSpecDataObj pageSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @param projectId
     * @return
     *     returns java.util.List<java.lang.Long>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCIDsForProject", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetCIDsForProject")
    @ResponseWrapper(localName = "getCIDsForProjectResponse", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetCIDsForProjectResponse")
    public List<Long> getCIDsForProject(
        @WebParam(name = "projectId", targetNamespace = "")
        ProjectIdDataObj projectId,
        @WebParam(name = "filterSpec", targetNamespace = "")
        MergedDefectFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamIds
     * @param filterSpec
     * @param pageSpec
     * @return
     *     returns com.coverity.ws.v6.MergedDefectsPageDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMergedDefectsForStreams", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetMergedDefectsForStreams")
    @ResponseWrapper(localName = "getMergedDefectsForStreamsResponse", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetMergedDefectsForStreamsResponse")
    public MergedDefectsPageDataObj getMergedDefectsForStreams(
        @WebParam(name = "streamIds", targetNamespace = "")
        List<StreamIdDataObj> streamIds,
        @WebParam(name = "filterSpec", targetNamespace = "")
        MergedDefectFilterSpecDataObj filterSpec,
        @WebParam(name = "pageSpec", targetNamespace = "")
        PageSpecDataObj pageSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamIds
     * @param filterSpec
     * @return
     *     returns java.util.List<java.lang.Long>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCIDsForStreams", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetCIDsForStreams")
    @ResponseWrapper(localName = "getCIDsForStreamsResponse", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetCIDsForStreamsResponse")
    public List<Long> getCIDsForStreams(
        @WebParam(name = "streamIds", targetNamespace = "")
        List<StreamIdDataObj> streamIds,
        @WebParam(name = "filterSpec", targetNamespace = "")
        MergedDefectFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamIds
     * @param cid
     * @return
     *     returns java.util.List<com.coverity.ws.v6.DefectChangeDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMergedDefectHistory", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetMergedDefectHistory")
    @ResponseWrapper(localName = "getMergedDefectHistoryResponse", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetMergedDefectHistoryResponse")
    public List<DefectChangeDataObj> getMergedDefectHistory(
        @WebParam(name = "cid", targetNamespace = "")
        Long cid,
        @WebParam(name = "streamIds", targetNamespace = "")
        List<StreamIdDataObj> streamIds)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @param projectId
     * @return
     *     returns java.util.List<com.coverity.ws.v6.ProjectMetricsDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTrendRecordsForProject", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetTrendRecordsForProject")
    @ResponseWrapper(localName = "getTrendRecordsForProjectResponse", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetTrendRecordsForProjectResponse")
    public List<ProjectMetricsDataObj> getTrendRecordsForProject(
        @WebParam(name = "projectId", targetNamespace = "")
        ProjectIdDataObj projectId,
        @WebParam(name = "filterSpec", targetNamespace = "")
        ProjectTrendRecordFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentIds
     * @param projectId
     * @return
     *     returns java.util.List<com.coverity.ws.v6.ComponentMetricsDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComponentMetricsForProject", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetComponentMetricsForProject")
    @ResponseWrapper(localName = "getComponentMetricsForProjectResponse", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetComponentMetricsForProjectResponse")
    public List<ComponentMetricsDataObj> getComponentMetricsForProject(
        @WebParam(name = "projectId", targetNamespace = "")
        ProjectIdDataObj projectId,
        @WebParam(name = "componentIds", targetNamespace = "")
        List<ComponentIdDataObj> componentIds)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectId
     * @return
     *     returns java.util.List<com.coverity.ws.v6.CheckerSubcategoryIdDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCheckerSubcategoriesForProject", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetCheckerSubcategoriesForProject")
    @ResponseWrapper(localName = "getCheckerSubcategoriesForProjectResponse", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetCheckerSubcategoriesForProjectResponse")
    public List<CheckerSubcategoryIdDataObj> getCheckerSubcategoriesForProject(
        @WebParam(name = "projectId", targetNamespace = "")
        ProjectIdDataObj projectId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamIds
     * @return
     *     returns java.util.List<com.coverity.ws.v6.CheckerSubcategoryIdDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCheckerSubcategoriesForStreams", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetCheckerSubcategoriesForStreams")
    @ResponseWrapper(localName = "getCheckerSubcategoriesForStreamsResponse", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetCheckerSubcategoriesForStreamsResponse")
    public List<CheckerSubcategoryIdDataObj> getCheckerSubcategoriesForStreams(
        @WebParam(name = "streamIds", targetNamespace = "")
        List<StreamIdDataObj> streamIds)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param fileId
     * @param streamId
     * @return
     *     returns com.coverity.ws.v6.FileContentsDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFileContents", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetFileContents")
    @ResponseWrapper(localName = "getFileContentsResponse", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetFileContentsResponse")
    public FileContentsDataObj getFileContents(
        @WebParam(name = "streamId", targetNamespace = "")
        StreamIdDataObj streamId,
        @WebParam(name = "fileId", targetNamespace = "")
        FileIdDataObj fileId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateTriageForCIDsInTriageStore", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.UpdateTriageForCIDsInTriageStore")
    @ResponseWrapper(localName = "updateTriageForCIDsInTriageStoreResponse", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.UpdateTriageForCIDsInTriageStoreResponse")
    public void updateTriageForCIDsInTriageStore(
        @WebParam(name = "arg0", targetNamespace = "")
        TriageStoreIdDataObj arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Long> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        DefectStateSpecDataObj arg2)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createMergedDefect", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.CreateMergedDefect")
    @ResponseWrapper(localName = "createMergedDefectResponse", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.CreateMergedDefectResponse")
    public void createMergedDefect(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamId
     * @param pageSpec
     * @return
     *     returns com.coverity.ws.v6.StreamFunctionPageDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStreamFunctionsInternal", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetStreamFunctionsInternal")
    @ResponseWrapper(localName = "getStreamFunctionsInternalResponse", targetNamespace = "http://ws.coverity.com/v6", className = "com.coverity.ws.v6.GetStreamFunctionsInternalResponse")
    public StreamFunctionPageDataObj getStreamFunctionsInternal(
        @WebParam(name = "streamId", targetNamespace = "")
        StreamIdDataObj streamId,
        @WebParam(name = "pageSpec", targetNamespace = "")
        PageSpecDataObj pageSpec)
        throws CovRemoteServiceException_Exception
    ;

}
